Array
(
    [FormKey] => 189
    [PatientUr] => 12345689
    [PatientDob] => 17/10/1971
    [PatientAge] => 40
    [PatientSex] => M
    [PatientSurname] => Ward
    [PatientFirstname] => Adam
    [PatientAddress] => Test address
    [PatientSuburb] => Sydney
    [PatientState] => New
    [PatientPostcode] => 2000
    [PatientEmail] => Adam@adamward.co.uk
    [PatientTel] => 07777777
    [PatientMob] => 07777777
    [StudyExamid] => 123456789
    [StudyDate] => 00/00/0000
    [StudyInstitution] => Test
    [StudyOperator] => 
    [StudyIndication] => Test
    [StudyTteToe] => 5
    [StudyQualityTd] => 6
    [StudyHeight] => 90.00
    [StudyWeight] => 90
    [StudyBsa] => 
    [StudyBmi] => 
    [StudyBp] => 
    [StudyHr] => 
    [VvLeftventricule] => 1
    [VvRightventricule] => 2
    [SfLeftventricule] => 2
    [SfRightventricule] => 2
    [EfLvedd] => 
    [EfLveda] => 
    [EfLvesd] => 
    [EfLvesa] => 
    [EfFs] => 
    [EfFac] => 
    [CoLvotd] => 
    [CoLvotvti] => 
    [CoHr] => 
    [CoCo] => 
    [CoCi] => 
    [Lafp] => 2
    [HaemodynamicState] => 1
    [PapLvotd] => 
    [PapLvotvti] => 
    [PapAvvti] => 
    [PapAva] => 
    [PapAvpg] => 
    [PapAvgm] => 
    [PapDimindex] => 
    [PapAljet] => 
    [PapAlpl] => 
    [PapAoroot] => 
    [PapAseao] => 
    [PapMvradius] => 
    [PapMvscale] => 
    [PapEro] => 
    [PapMvpl2t] => 
    [PapMvgp] => 
    [PapMvgm] => 
    [PapPa] => 
    [PapCwmr] => 
    [PapMva] => 
    [DfE] => 
    [DfA] => 
    [DfDt] => 
    [DfS] => 
    [DfPadur] => 
    [DfAdE] => 
    [DfEe] => 
    [DfIvrt] => 
    [DfAdur] => 
    [DfSd] => 
    [DfEa] => 
    [LvLvh] => 0
    [LvIvswt] => 
    [LvPwt] => 
    [LvLvmass] => 
    [LvLvimass] => 
    [VaExamined] => 3
    [VaStenosys] => 7
    [VaRegurgitation] => 9
    [VaPericardialEffusion] => 
    [AtriaLaDiam] => 10
    [AtriaRaDiam] => 3
    [AtriaLaArea] => 5
    [AtriaRaArea] => 5
    [AtriaTrvMax] => 5
    [AtriaTvgr] => 5
    [AtriaRap] => 3
    [AtriaRsvp] => 10
    [Comments] => 
    [AddedDate] => 2011-11-17 23:23:06
    [FormComplete] => 1
    [CreatedBy] => 82
    [FormMedia] => 0
    [pdffile] => 12345689-2011-11-17-7349.pdf
    [StudyRhythm] => 
    [status] => OK
)
