<?php

	$db = new MySQLi (DB_HOST, DB_USERNAME, DB_PASSWORD, DB_DATABASE);
//	$db_user = new MySQLi (DB_HOST, DB_USERNAME, DB_PASSWORD, DB_DATABASE);
	$db_user = new MySQLi (DB_USER_HOST, DB_USER_USERNAME, DB_USER_PASSWORD, DB_USER_DATABASE);